### ISSUE TITLE
Upgraded 'build.zig' to '0.12.0', need help and want to contribute

### ISSUE THREAD

**Issue by wisonye** [Linouth/zig-pico-sdk#1]
Hi there, thanks for your efforts, that's exactly what I have been looking for for a very long time:)

I've already upgraded the `build.zig` to `0.12.0` version:

- Fixed all breaking change stuff
- Added `PICO_TOOLCHAIN_ARM_STD_INCLUDE` env var support, as every user installs `Arm toolchain` in different ways

But my version still has the following error:

```bash
# Build on MacOS with zig 0.12.0
PICO_TOOLCHAIN_ARM_STD_INCLUDE=/Users/wison/Downloads/arm-gnu-toolchain/arm-none-eabi/include zig build --summary all

Build Summary: 0/4 steps succeeded; 1 failed
install transitive failure
└─ install generated to testbin transitive failure
   ├─ testbin transitive failure
   │  └─ zig build-obj testbin Debug thumb-freestanding-eabi 2 errors
   └─ testbin (+1 more reused dependencies)
src/main.zig:2:11: error: C import failed
const c = @cImport({
          ^~~~~~~~
src/main.zig:2:11: note: libc headers not available; compilation does not link against libc
referenced by:
    main: src/main.zig:9:5
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/Users/wison/pico/zig-pico-sdk/pico-sdk/src/common/pico_base/include/pico.h:20:10: error: 'pico/version.h' file not found
#include "pico/version.h"
         ^
```

So, I had a look a the `pico-sdk/src/common/pico_base/include/pico/version.h`, but doesn't exists, as the correct filename is `version.h.in`:

```bash
cat pico-sdk/src/common/pico_base/include/pico/version.h.in

/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
// ---------------------------------------

#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H

#define PICO_SDK_VERSION_MAJOR    ${PICO_SDK_VERSION_MAJOR}
#define PICO_SDK_VERSION_MINOR    ${PICO_SDK_VERSION_MINOR}
#define PICO_SDK_VERSION_REVISION ${PICO_SDK_VERSION_REVISION}
#define PICO_SDK_VERSION_STRING   "${PICO_SDK_VERSION_STRING}"

#endif
```

As you can see, that file should be generated by another `cmake`, and I found that:

```bash
rg "version.h.in" ./pico-sdk/

./pico-sdk/src/common/pico_base/generate_config_header.cmake
25:configure_file( ${CMAKE_CURRENT_LIST_DIR}/include/pico/version.h.in ${CMAKE_BINARY_DIR}/generated/pico_base/pico/version.h)
```

It seems somehow in the `build.zig`, you need to run `./pico-sdk/src/common/pico_base/generate_config_header.cmake` before the build....:)

I think that's related to the following code in your `build.zig`:

```zig
        // TODO: This include is tricky. This is generated on calling 'cmake',
        // either for the project (in zig-cache/cmake) or pico-sdk itself.
        // Preferably this will be generated in cache, but the CMakeFile.txt
        // file requires the to be linked obj file as well.
        // One solution could be to run `cmake ../../pico-sdk` from a folder in
        // zig-cache.
        const generated = builder.pathJoin(&.{ PATH, "pico-sdk/build/generated/pico_base" });
        obj.addSystemIncludePath(.{ .path = generated });
```

**Comment by wisonye** [comment]
I'm not sure if I understand your `build.zig` logic correctly or not:

```zig
    pub fn init(
        builder: *std.build.Builder,
        zig_bin_name: []const u8,
        zig_root_src: []const u8,
    ) !*PicoExe {
         // ... ingore code above
         const self = builder.allocator.create(PicoExe) catch unreachable;
         self.* = PicoExe{
             .builder = builder,
             .step = std.build.Step.init(.{
                 .id = base_id,
                 .name = name,
                 .owner = builder,
                 .makeFn = make,
             }),
             .name = name,
             .zig_obj = obj,
             .output_bin = .{ .step = &self.step },

             .pio_files = std.ArrayList([]const u8).init(builder.allocator),
         };

         self.step.dependOn(&obj.step);

        return self;
    }

    ///
    ///
    ///
    pub fn make(step: *std.build.Step, prog_node: *std.Progress.Node) anyerror!void {
        _ = prog_node;
        const log = std.log.scoped(.PicoExe);
        log.info(">>> Creating build directory and CMakeLists file for the pico-sdk", .{});

        const self = @fieldParentPtr(PicoExe, "step", step);
        const builder = self.builder;

        // Here!!!
        const zig_obj_path = self.zig_obj.getOutputSource().getPath(builder);
        // ... ignore code below
    }

    const pico_exe = try PicoExe.init(b, "testbin", "src/main.zig");

    pico_exe.install();
```

That said by calling `init()` to create the `PicoExe` instance and `pico_exe.step` (cmake step) depends on the `pico_exe.zig_obj` step, but the error comes from `pico_exec.zig_obj`step said that it can't find the file (`${CMAKE_BINARY_DIR}/generated/pico_base/pico/version.h`) that should generated by `pico_exec.step`, so it's a dead cycle?:)

If I change the logic to let `pico_exe.zig_obj` step depends on `pico_exe.step` (cmake step), it also doesn't work, as in your `make` function (before running cmake command) has the following line:

```zig
        const zig_obj_path = self.zig_obj.getOutputSource().getPath(builder);
```

That asks for the `zig_obj` step has to been done and .... is that possible?:)

**Comment by Linouth** [comment]
Hey, glad this project is of some help! Apologies for the messy state of it ;)

I have not touched this in quite some time, I've just build it from scratch again for a quick refresher.
 Your issue with the version.h file can be solved by going into the pico-sdk folder and running cmake there. So running `mkdir build && cd build && cmake ..` inside `pico-sdk/`. This runs the cmake tasks to generate the `pico-sdk/build/generated/pico_base` include folder.

You are right that there is a bit of a reference loop. The zig code needs the SDK which makes use of those generated header files, however those files only get generated by CMake. And CMake needs the object file generated from our zig code. This is exactly what the code and comment you mentioned refers to. 

So we can't just switch the order of the tasks. But like you said, we should run the relevant CMake tasks before compiling the zig object file and let it generate those headers inside the cache. I think the simplest would be to just run `cmake -S pico-sdk -B zig-cache/cmake-pre` in another step before compiling the zig code. Then add `zig-cache/cmake-pre/generated/pico_base` as systemIncludeDir.

Thanks for looking into this. Would be nice to have an updated version working!

**Comment by wisonye** [comment]
> Hey, glad this project is of some help! Apologies for the messy state of it ;)
> 
> I have not touched this in quite some time, I've just build it from scratch again for a quick refresher. Your issue with the version.h file can be solved by going into the pico-sdk folder and running cmake there. So running `mkdir build && cd build && cmake ..` inside `pico-sdk/`. This runs the cmake tasks to generate the `pico-sdk/build/generated/pico_base` include folder.
> 
> You are right that there is a bit of a reference loop. The zig code needs the SDK which makes use of those generated header files, however those files only get generated by CMake. And CMake needs the object file generated from our zig code. This is exactly what the code and comment you mentioned refers to.
> 
> So we can't just switch the order of the tasks. But like you said, we should run the relevant CMake tasks before compiling the zig object file and let it generate those headers inside the cache. I think the simplest would be to just run `cmake -S pico-sdk -B zig-cache/cmake-pre` in another step before compiling the zig code. Then add `zig-cache/cmake-pre/generated/pico_base` as systemIncludeDir.
> 
> Thanks for looking into this. Would be nice to have an updated version working!

Thanks for the quick reply, I will have a look later today or tomorrow when I have time:)

Also, would you accept any new testing branch and pull requests? (or you don't have an interest in this topic anymore at this moment).

That's because I'm handling `using Zig to write Pi SDK demo` proactively and I want to make improvements to this topic (like a guide tutorial with detailed demos), if you don't want too many commits, then I think I better to fork your repo and do whatever I want to improve:) No matter what, huge thanks for what you have done so far:)

**Comment by Linouth** [comment]
I am still interested in this as I still have some project ideas I'd like to try out on the RP2040. Though, currently I do not have time and energy to work on this. 
Pull requests are appreciated, but it can take some time for me to handle them. Feel free to fork the project though!

I might look into this again in some time. I really want to get my Zig and Zig build system knowledge up to date.
Also, the people behind pico-sdk were working on compatibility with Clang. This might be working by now, meaning that cmake could be replaced completely by the zig build system, which might be interesting.

**Comment by wisonye** [comment]
> I am still interested in this as I still have some project ideas I'd like to try out on the RP2040. Though, currently I do not have time and energy to work on this. Pull requests are appreciated, but it can take some time for me to handle them. Feel free to fork the project though!
> 
> I might look into this again in some time. I really want to get my Zig and Zig build system knowledge up to date. Also, the people behind pico-sdk were working on compatibility with Clang. This might be working by now, meaning that cmake could be replaced completely by the zig build system, which might be interesting.

Thanks, actually, I've already figured out and solved all of the building issues, and integrated them into my tutorial in detail, feel free to come and have a look when you need to:)

https://github.com/wisonye/embedded-tutorial-with-rp2040
